config/routes.rb
Rails.application.routes.draw do
   resources :categories do
      resources :posts
   end 

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :posts, dependent: :destroy
	validates :name, presence: true,
                    length: { maximum: 500 }
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :category
  validates :title, presence: true,
                    length: { maximum: 500 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
	def index
	    @categories = Category.all
	end

	def show
	    @category = Category.find(params[:id])
	end
		
	
	def new
	  @category = Category.new
	end

	def edit
	  @category = Category.find(params[:id])
	end


	def create
		@category = Category.new(category_params)
         
        if @category.save
			redirect_to @category
        else
        	render 'new'
        end
	end

	def update
	  @category = Category.find(params[:id])
	 
	  if @category.update(category_params)
	    redirect_to @category
	  else
	    render 'edit'
	  end
	end


	def destroy
	  @category = Category.find(params[:id])
	  @category.destroy
	 
	  redirect_to categories_path
	end


	private
	  def category_params
	    params.require(:category).permit(:name)
	  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	def create
    @category = Category.find(params[:category_id])
    @post = @category.posts.create(post_params)
    redirect_to category_path(@category)
    end
 
	def destroy
	    @category = Category.find(params[:category_id])
	    @post = @category.posts.find(params[:id])
	    @post.destroy
	    redirect_to category_path(@category)
	end


    private
	    def post_params
	      params.require(:post).permit(:title, :description)
	    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/categories/_form.html.erb
<%= form_for @category do |f| %>
 
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@category.errors.count, "error") %> prohibited
        this category from being saved:
      </h2>
      <ul>
        <% @category.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
 
<% end %>

app/views/categories/edit.html.erb
<h1>Edit category</h1>
 
<%= render 'form' %>

 
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<h1>Listing categories</h1>

<%= link_to 'New category', new_category_path %>

<table>
  <tr>
    <th>Name</th>
    <th colspan="3"></th>
  </tr>
 
  <% @categories.each do |category| %>
    <tr>
      <td><%= category.name %></td>
      <td><%= link_to 'Show', category_path(category) %></td>
      <td><%= link_to 'Edit', edit_category_path(category) %></td>
      <td><%= link_to 'Destroy', category_path(category),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>

app/views/categories/new.html.erb
<h1>New Category</h1>


<%= render 'form' %>


<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @category.name %>
</p>

<h2>Posts</h2>
<%= render @category.posts %>

<h2>Add a post:</h2>
<%= render 'posts/form' %>


<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_for([@category, @category.posts.build]) do |f| %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/posts/_post.html.erb
<p>
  <strong>Title:</strong>
  <%= post.title %>
</p>
 
<p>
  <strong>Description:</strong>
  <%= post.description %>
</p>

<p>
  <%= link_to 'Destroy Post', [post.category, post],
               method: :delete,
               data: { confirm: 'Are you sure?' } %>
</p>